#:schema node_modules/wrangler/config-schema.json
name = "test"
main = "src/index.ts"
compatibility_date = "2024-12-02"
account_id = "37863d8a0916ceea23ac3152e73b3ce6"

[assets]
directory = "./public"
